baseURL = "https://example.com"
title = "Les chiffres du Covid-19 en France"
themesDir = "../leschiffresducovid.github.io/"
theme = "m10c"
paginate = 20

[markup.goldmark.renderer]
  unsafe = true

[params]
  author = "NR"
  description = "Une autre présentation des données officielles"
  avatar = "ambulance.jpg"
  [[params.social]]
    name = "github"
    url = "https://github.com/leschiffresducovid"
  [[params.social]]
    name = "mail"
    url = "mailto:leschiffresducovid@gmx.com"


  # Brown theme
  #[params.style]
  #  darkestColor = "#463625"
  #  darkColor = "#2a3738"
  #  primaryColor = "#eeee6a"
  #  lightColor = "#96a879"
  #  lightestColor = "#ffffff"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"

  # Red and black theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  primaryColor = "#ffffff"
  #  lightColor = "#a2a2a2"
  #  lightestColor = "#d3d3d3"
